services:
  ansible:
    image: rhel8-ansible
    volumes:
      - ./ansible:/home/tcarter/ansible/
    command: /usr/sbin/sshd -D

  host1:
    image: rhel8-ansible
    command: /usr/sbin/sshd -D

  host2:
    image: rhel8-ansible
    command: /usr/sbin/sshd -D

networks:
  default:
    name: nifi_network

# volumes:
#   ansible_vol:
  
# docker compose -f docker-compose.yaml up -d
# docker ps -a
# docker exec -it cluster-ansible-1 bash

# docker compose -f docker-compose.yaml down