---
ansible_become: true
ansible_become_method: sudo
ansible_user: root #ansible

nifi_log_level_root: WARN
nifi_version: 1.26.0
nifi_tar_file: "nifi-{{ nifi_version }}-bin.zip" #"nifi-{{ nifi_version }}-bin.tar.gz"
nifi_log_level_org_apache_nifi_bootstrap: DEBUG
nifi_authorized_nodes_list:
# stuff entered here

#NiFi Cluster Settings
nifi_single_node: false
nifi_cluster_node_protocol_port: 11443
nifi_web_http_port: 8080
nifi_web_https_port: 9443
nifi_remote_input_http_enabled: true
nifi_remote_input_socket_port: 10443
nifi_remote_input_secure: true
nifi_provenance_rollover_time: 30 secs
nifi_provenance_max_storage_size: 500 GB
nifi_provenance_max_storage_time: 24 hours
nifi_provenance_implementation: WriteAheadProvenanceRepository
nifi_content_always_sync: false
nifi_content_archive_max_usage_percentage: 50%
nifi_content_archive_max_rentention_period: 3 hours
nifi_content_claim_max_appendable_size: 1 MB
nifi_content_archive_enabled: false
nifi_queue_swap_threshold: 100000
nifi_swap_in_period: 5 sec
nifi_swap_in_threads: 1
nifi_swap_out_period: 5 sec
nifi_swap_out_threads: 4
nifi_base_dir: /opt/nifi
nifi_provenance_repository: "{{ nifi_base_dir }}/repos/provenance_repository"
nifi_content_repository: "{{ nifi_base_dir }}/repos/content_repository"
nifi_flowfile_repository: "{{ nifi_base_dir }}/flowfile_repository"
nifi_database_repository: "{{ nifi_base_dir }}/database_repository"
nifi_sensitive_props_key: this_stinks
nifi_initial_admin: nifi-admin

###### NiFi zookeeper settings
nifi_zookeeper_servers:
  - 192.168.1.1

nifi_zookeeper_dir: /var/lib/storage/HDD/zookeeper
nifi_state_management_embedded_zookeeper_start: False #false?
nifi_zookeeper_root_node: /var/lib/storage/HDD/zookeeper

##### security sesttings
nifi_is_secure: true
nifi_security_truststorePasswd: 123456
nifi_security_truststoreType: JKS
nifi_security_keystore: "{{ nifi_base_dir }}/truststore.jks"
nifi_security_keystorePasswd: 123456
nifi_security_keystoreType: JKS
nifi_security_keystore: "{{ nifi_base_dir }}/{{ inventory_hostname }}.jks"
#nifi_need_client_auth: true
#cert_path: /etc/pki/tls/certs
nifi_node_jvm_memory: 337g

##### Authentication